# Generated by Django 3.1.5 on 2021-01-27 13:55

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Up to 11 digits allowed.", regex='^\\d{11}$')])),
                ('suggestion_text', models.TextField()),
                ('published_date', models.DateTimeField(default=datetime.datetime(2021, 1, 27, 13, 55, 24, 101550, tzinfo=utc))),
            ],
        ),
    ]
