# Generated by Django 3.1.5 on 2021-01-27 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
