# Generated by Django 3.1.5 on 2021-02-01 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210127_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=200)),
                ('child_last_name', models.CharField(max_length=200)),
                ('child_dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('parent_name', models.CharField(max_length=200)),
                ('phone_number_1', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Up to 11 digits allowed.", regex='^\\d{11}$')])),
                ('phone_number_2', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Up to 11 digits allowed.", regex='^\\d{11}$')])),
                ('genotype', models.CharField(choices=[('AA', 'Very Strong'), ('AS', 'Strong'), ('SS', 'Not so strong')], max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('medical_condition', models.TextField()),
            ],
        ),
    ]
