# Generated by Django 3.1.5 on 2021-02-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='child_dob',
            new_name='student_dob',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='child_first_name',
            new_name='student_first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='child_last_name',
            new_name='student_last_name',
        ),
        migrations.AddField(
            model_name='students',
            name='student_pic',
            field=models.ImageField(default='student/placeholder.jpg', upload_to='student_pic'),
        ),
        migrations.AlterField(
            model_name='students',
            name='genotype',
            field=models.CharField(choices=[('AA', 'Very Strong'), ('AS', 'Quite Strong'), ('SS', 'Not so strong')], max_length=3),
        ),
    ]
