# Generated by Django 3.1.5 on 2021-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210201_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='class_choices',
            field=models.CharField(choices=[('KD', 'Kindergaten'), ('PN', 'Pre-Nursery'), ('NU', 'Nursery'), ('PR', 'Primary'), ('JSS', 'Junior'), ('SSS', 'Senior')], default='Kindergaten', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(default='placeholder.jpg', upload_to='student_pic'),
        ),
    ]
