# Generated by Django 3.1.5 on 2021-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210201_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_choices',
            field=models.CharField(choices=[('KD', 'Kindergaten'), ('PN', 'Pre-Nursery'), ('NU', 'Nursery'), ('PR', 'Primary'), ('JSS', 'Junior'), ('SSS', 'Senior')], default='Kindergaten', help_text='Please click on this to select the class you are applying for', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], default='AA', help_text='Please click on this to select the Genotype of your child', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateField(help_text='Please enter in the format yyyy-mm-dd'),
        ),
    ]
