# Generated by Django 3.1.5 on 2021-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210201_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=200)),
                ('subject_category', models.CharField(choices=[('KD', 'Kindergaten'), ('PN', 'Pre-Nursery'), ('NU', 'Nursery'), ('PR', 'Primary'), ('JSS', 'Junior'), ('SSS', 'Senior')], default='Kindergaten', help_text='Please click on this to select the category the subject falls under', max_length=15)),
            ],
        ),
    ]
