# Generated by Django 3.1.5 on 2021-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_category',
            field=models.CharField(choices=[('N&P', 'Nursery & Primary'), ('JSS', 'Junior'), ('SSS', 'Senior')], default='Kindergaten', help_text='Please click on this to select the category the subject falls under', max_length=15),
        ),
    ]
